### ISSUE TITLE
[Bug]: type:"module"时无法执行app-tools的dev指令

### ISSUE THREAD

**Issue by KotoriK** [web-infra-dev/modern.js#3338]
### 版本信息

```sh
devDependencies:
@modern-js/app-tools 2.11.0
```

## 简述
项目为ES Module项目时(package.json配置```"type": "module"```)，无法加载开发服务器，报错：
```
C:\apps\public-landing\node_modules\.cache\node-bundle-require\modern.config.js-1680515795661.{hash}.bundled.cjs:11
  plugins: [(0, import_app_tools.default)()]

TypeError: Get Error while loading config file: C:\apps\public-landing\modern.config.js, please check it and retry.
(0 , import_app_tools.default) is not a function
    at Object.<anonymous> (C:\apps\public-landing\node_modules\.cache\node-bundle-require\modern.config.js-1680515795661.{hash}.bundled.cjs:11:13)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bundleRequire (C:\node_modules\.pnpm\@modern-js+node-bundle-require@2.11.0_biqbaboplfbrettd7655fr4n2y\node_modules\@modern-js\node-bundle-require\dist\cjs\index.js:32:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async bundleRequireWithCatch (C:\node_modules\.pnpm\@modern-js+core@2.11.0_biqbaboplfbrettd7655fr4n2y\node_modules\@modern-js\core\dist\config\loadConfig.js:68:21)
```
### modern.js内容
```js
const appTools = require('@modern-js/app-tools');
const { defineConfig } = require('@modern-js/app-tools');

// https://modernjs.dev/docs/apis/app/config
module.exports = defineConfig({
  runtime: {
    router: true,
  },
  plugins: [appTools()],
});
```
### modern.config.js-1680515795661.{hash}.bundled.cjs 内容
```js
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// modern.config.js
var modern_config_exports = {};
__export(modern_config_exports, {
  default: () => modern_config_default
});
module.exports = __toCommonJS(modern_config_exports);
var import_app_tools = __toESM(require("@modern-js/app-tools"), 1);
console.log(import_app_tools.default);
var modern_config_default = (0, import_app_tools.defineConfig)({
  runtime: {
    router: true
  },
  plugins: [(0, import_app_tools.default)()]
});
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {});
```

### 复现链接

无

### 复现步骤

安装依赖后，修改```modern.config.js```为上述内容，运行```modern dev```。
```modern.config.ts```也有同样的问题

**Comment by chenjiahan** [comment]
请问 app-tools 为什么需要把 packge.json 的 type 设置为 "module" 喔？

具体是什么样的使用场景

**Comment by KotoriK** [comment]
更为具体的场景是这样的：
```tsconfig.json```的```moduleResolution```设置为```nodenext```时，如果这个项目不是ES Module(package.json中type不为module)，而要导入的包是ES Module，则会报ts(1479)(当前文件是 CommonJS 模块，其导入将生成“require”调用；但是，引用的文件是 ECMAScript 模块，它不能使用“require”进行导入。) 

提这个issue主要是发现```modern.config.ts```编译后的代码错误地给```@modern-js/app-tool```的导入添加了```__toESM```这个helper。此外，提这个issue的**目的不是希望把```@modern-js/app-tool```的type设置为module**，而是指出目前在```type:module```的工程中```modern.js```因为不能正常启动的问题。

**Comment by chenjiahan** [comment]
嗯嗯，get 了~

目前 `type:module` 的工程中确实存在这个问题，原因是 Modern.js 会通过 esbuild 来打包 modern.config.ts 文件，而 esbuild 会自动读取 package.json 中的 `type:module` 并对产物进行特殊处理。（[相关文档](https://esbuild.github.io/content-types/#default-interop)）。

我们近期会研究一下怎么处理这个问题。

**Comment by 10Derozan** [comment]
两种改造方式，一种我们的包提供name export的形式，另一种是所有包都改造成Pure ESM的格式

**Comment by chenjiahan** [comment]
改造为 Pure ESM 的成本太高了，目前可以考虑提供 named exports，或在 bundle-require 内通过一些 hack 逻辑来规避 esbuild 的行为

**Comment by chenjiahan** [comment]
这个问题已经在 v2.25.0 版本中解决，在新版本中，所有插件都可以通过 named import 导入，从而避免这个问题。

参考：

- https://github.com/web-infra-dev/modern.js/issues/4032
