### ISSUE TITLE
[Bug]: 启用 ssg 部署到github page，页面显示水合错误

### ISSUE THREAD

**Issue by a145789** [web-infra-dev/modern.js#3404]
### 版本信息

```sh
System:
    OS: Windows 10 10.0.25336
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Memory: 8.61 GB / 15.92 GB
  Browsers:
    Edge: Spartan (44.25336.1000.0), Chromium (112.0.1722.34)
    Internet Explorer: 11.0.25336.1000
  npmPackages:
    @modern-js/app-tools: 2.12.0 => 2.12.0
    @modern-js/builder-rspack-provider: 2.12.0 => 2.12.0
    @modern-js/eslint-config: 2.12.0 => 2.12.0
    @modern-js/plugin-ssg: 2.12.0 => 2.12.0
    @modern-js/runtime: 2.12.0 => 2.12.0
    @modern-js/tsconfig: 2.12.0 => 2.12.0
```

### 问题详情

启用 ssg 后，page 文件只展示 `<div>123</div>`，其余未修改。
modern.config.ts 配置为
```ts
import appTools, { defineConfig } from '@modern-js/app-tools';
import ssgPlugin from '@modern-js/plugin-ssg';

// https://modernjs.dev/en/configure/app/usage
export default defineConfig<'rspack'>({
  output: {
    ssg: true,
    disableSourceMap: true,
    assetPrefix: './',
    distPath: {
      html: '',
    },
  },
  html: {
    title: 'resume',
    disableHtmlFolder: true,
  },
  runtime: {
    router: true,
  },
  plugins: [
    appTools({
      bundler: 'experimental-rspack',
    }),
    ssgPlugin(),
  ],
});
```

本地无错误部署到 github page ，无内容显示，控制台报错，[地址](https://a145789.github.io/modern-test/)。
打开控制台就可以看到
```js
b-react.ed09f625.js:1 Uncaught Error: Minified React error #425; visit https://reactjs.org/docs/error-decoder.html?invariant=425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at rv (lib-react.ed09f625.js:1:40445)
    at lib-react.ed09f625.js:1:101084
    at oV (lib-react.ed09f625.js:1:106597)
    at oU (lib-react.ed09f625.js:1:99542)
    at lib-react.ed09f625.js:1:99348
    at oI (lib-react.ed09f625.js:1:99356)
    at oC (lib-react.ed09f625.js:1:94393)
    at S (builder-runtime~lib-polyfill~lib-react~lib-router~main.956716a9.js:1:72752)
    at C (builder-runtime~lib-polyfill~lib-react~lib-router~main.956716a9.js:1:73282)
    at I.<computed> (lib-polyfill.b751aee4.js:1:81390)
rv @ lib-react.ed09f625.js:1
（匿名） @ lib-react.ed09f625.js:1
oV @ lib-react.ed09f625.js:1
oU @ lib-react.ed09f625.js:1
（匿名） @ lib-react.ed09f625.js:1
oI @ lib-react.ed09f625.js:1
oC @ lib-react.ed09f625.js:1
S @ builder-runtime~lib-polyfill~lib-react~lib-router~main.956716a9.js:1
C @ builder-runtime~lib-polyfill~lib-react~lib-router~main.956716a9.js:1
I.<computed> @ lib-polyfill.b751aee4.js:1
T @ lib-polyfill.b751aee4.js:1
P @ lib-polyfill.b751aee4.js:1
3lib-react.ed09f625.js:1 Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ly (lib-react.ed09f625.js:1:46741)
    at i (lib-react.ed09f625.js:1:118174)
    at oU (lib-react.ed09f625.js:1:99482)
    at lib-react.ed09f625.js:1:99348
    at oI (lib-react.ed09f625.js:1:99356)
    at oC (lib-react.ed09f625.js:1:94393)
    at S (builder-runtime~lib-polyfill~lib-react~lib-router~main.956716a9.js:1:72752)
    at C (builder-runtime~lib-polyfill~lib-react~lib-router~main.956716a9.js:1:73282)
    at I.<computed> (lib-polyfill.b751aee4.js:1:81390)
    at T (lib-polyfill.b751aee4.js:1:81155)
ly @ lib-react.ed09f625.js:1
i @ lib-react.ed09f625.js:1
oU @ lib-react.ed09f625.js:1
（匿名） @ lib-react.ed09f625.js:1
oI @ lib-react.ed09f625.js:1
oC @ lib-react.ed09f625.js:1
S @ builder-runtime~lib-polyfill~lib-react~lib-router~main.956716a9.js:1
C @ builder-runtime~lib-polyfill~lib-react~lib-router~main.956716a9.js:1
I.<computed> @ lib-polyfill.b751aee4.js:1
T @ lib-polyfill.b751aee4.js:1
P @ lib-polyfill.b751aee4.js:1
lib-react.ed09f625.js:1 Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at i (lib-react.ed09f625.js:1:117838)
    at oU (lib-react.ed09f625.js:1:99482)
    at lib-react.ed09f625.js:1:99348
    at oI (lib-react.ed09f625.js:1:99356)
    at o_ (lib-react.ed09f625.js:1:96107)
    at oC (lib-react.ed09f625.js:1:94662)
    at S (builder-runtime~lib-polyfill~lib-react~lib-router~main.956716a9.js:1:72752)
    at C (builder-runtime~lib-polyfill~lib-react~lib-router~main.956716a9.js:1:73282)
    at I.<computed> (lib-polyfill.b751aee4.js:1:81390)
    at T (lib-polyfill.b751aee4.js:1:81155)
i
```

相关：https://github.com/vercel/next.js/discussions/35773

可能是我 modern.config 的配置有问题？

### 复现链接

https://github.com/a145789/modern-test

### 复现步骤

本地开发无问题，只部署到github page上有问题

**Comment by a145789** [comment]
hello，请问一下目前这个问题有跟进么？因为有个项目在使用这个东西，如果目前没有人力支持，就先切其他方案了。

**Comment by chenjiahan** [comment]
@GiveMe-A-Name 会负责跟进这个问题

@a145789 如果比较着急的话，可以先切换到 webpack 构建模式喔，webpack 模式是比较稳定的，Rspack 模式仍在快速迭代中

**Comment by a145789** [comment]
好的

**Comment by GiveMe-A-Name** [comment]
目前 Modern.js SSG 还不支持与嵌套路由进行配置。你 build 出来的产物不算是 SSG，理论上来说应该走的是 CSR，不会有报错。

至于这个报错，本地没复现出来。我待会试下部署到 github page 上看看能不能复现这个问题

**Comment by zllkjc** [comment]
这边的 404 是客户端路由的 404，这是因为生成器生成的项目默认会使用 React Router（目录结构为 `src/routes`，嵌套路原结构）。然后，github page 会默认带上仓库名作为 baseUrl，这里是 `/modern-test`，而项目此时的 baseUrl 其实是 `/`。因此无法匹配路由，就出现了 404。

根据需求，有以下两种解决方案：
1. 项目实际上不需要客户端路由，可以把 `src/routes` 移除，并将配置中的 runtime.router 设置为 false，新建 [`src/App.tsx`](https://modernjs.dev/guides/concept/entries.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%B7%AF%E7%94%B1)，直接写单个页面的代码。
2. 设置 [`server.baseUrl`](https://modernjs.dev/configure/app/server/base-url.html) 为 `/modern-test`。

**Comment by a145789** [comment]
按照方式1修改了下，想问下当前有配置项将 main.html 改为 index.html 么？在文档里找了下，好像 filename 里也没有支持修改 html name 的 api

**Comment by chenjiahan** [comment]
在 Modern.js 单入口应用中，默认的入口名为 main，这个行为目前没有配置项可以修改，不过可以考虑添加一个选项来控制默认入口的名称。

@zllkjc 你觉得嘞

**Comment by a145789** [comment]
找到了一个办法
```ts
export default defineConfig({
 // ...
  tools: {
    htmlPlugin: {
      filename: 'index.html',
    },
  },
});

```

不过用这个配置项 build 后会报错，但是构建后的产物部署后看着展示没问题

**Comment by a145789** [comment]
```
error   error   Web Server Error - Internal server error, error = Error: Could not find template file: D:\workpack_2\resume\dist\main.html                                                                    
    at ModernServer.render [as routeRenderHandler] (D:\workpack_2\resume\node_modules\.pnpm\registry.npmjs.org+@modern-js+prod-server@2.12.0_react-dom@18.2.0_react-router-dom@6.10.0_react@18.2.0\node_modules\@modern-js\prod-server\dist\cjs\libs\render\index.js:60:11)
    at ModernServer.handleWeb (D:\workpack_2\resume\node_modules\.pnpm\registry.npmjs.org+@modern-js+prod-server@2.12.0_react-dom@18.2.0_react-router-dom@6.10.0_react@18.2.0\node_modules\@modern-js\prod-server\dist\cjs\server\modernServer.js:288:37)
    at ModernServer.routeHandler (D:\workpack_2\resume\node_modules\.pnpm\registry.npmjs.org+@modern-js+prod-server@2.12.0_react-dom@18.2.0_react-router-dom@6.10.0_react@18.2.0\node_modules\@modern-js\prod-server\dist\cjs\server\modernServer.js:379:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5), req.url = /, req.headers = { host: 'localhost:8080' }
```

应该是 dist 目录下生成了 router.json 这个文件，我使用了
```
runtime: {
    router: false,
},
```
dist目录下面生成了 route.json
```json
{
  "routes": [
    {
      "urlPath": "/index",
      "entryName": "main",
      "entryPath": "main.html",
      "isSPA": true,
      "isSSR": false
    }
  ]
}
```

**Comment by a145789** [comment]
ok，使用第二种方式完美解决，感谢。
