### ISSUE TITLE
[Bug]: 无法识别`node:path`

### ISSUE THREAD

**Issue by zhangfisher** [web-infra-dev/modern.js#3972]
### 版本信息

```sh
"@modern-js/module-tools": "^2.10.0"


import moduleTools, { defineConfig } from '@modern-js/module-tools'
import type { CliPlugin, ModuleTools } from '@modern-js/module-tools';
import copy from "esbuild-copy-files-plugin";

const esbuildOptions = {
  plugins: [
    //@ts-ignore
    copy({
      source: ['package.json', 'README.md', 'LICENSE'],
      target: "dist/"
    })
  ],
  banner: {
    js: `/**
*        
*   ---=== FlexTools ===---
*   https://zhangfisher.github.com/flex-tools
* 
*   一些实用工具函数
*
*/`}
}

const ModulePlugin = (): CliPlugin<ModuleTools> => ({
  name: 'module',
  setup: () => ({
    modifyLibuild(config) {
      config.esbuildOptions = c => {
        c.banner = esbuildOptions.banner;
        c.plugins?.push(...esbuildOptions.plugins);
        c.entryNames = '[dir]/[name]'
        c.chunkNames = '[name]-[hash]';
        if (config.format === 'esm') {
          c.outExtension = { '.js': '.mjs' }
        }
        return c;
      };
      return config;
    },
  }),
});

export default defineConfig({
  plugins: [moduleTools(), ModulePlugin()],
  buildConfig: [
    {
      input: ['src'],
      format: 'esm',
      splitting: true,
      sourceMap: false,
      minify: 'esbuild',
      dts: false,
      target: 'es2021',
    },
    {
      buildType: 'bundleless',
      dts: {
        only: true
      }
    },
    {
      input: ['src'],
      format: 'cjs',
      splitting: true,
      sourceMap: false,
      minify: 'esbuild',
      dts: false,
      target: 'es2021',
    },
  ]
}) 
```
```


### 问题详情

```shell


error   ModuleBuildError: 

╭───────────────────────╮
│ bundle failed:        │
│  - format is "cjs"    │
│  - target is "es2021" │
╰───────────────────────╯

Detailed Information: 
Build failed with 6 error, 0 warning:

[LIBUILD:NODE_RESOLVE_FAILED] Can't resolve 'node:path' in 'E:\Work\Code\sources\flex-tools\src\misc'

[LIBUILD:NODE_RESOLVE_FAILED] Can't resolve 'node:path' in 'E:\Work\Code\sources\flex-tools\src\package'

[LIBUILD:NODE_RESOLVE_FAILED] Can't resolve 'node:path' in 'E:\Work\Code\sources\flex-tools\src\package'

[LIBUILD:NODE_RESOLVE_FAILED] Can't resolve 'node:fs' in 'E:\Work\Code\sources\flex-tools\src\package'

[LIBUILD:NODE_RESOLVE_FAILED] Can't resolve 'node:path' in 'E:\Work\Code\sources\flex-tools\src\package'

[LIBUILD:NODE_RESOLVE_FAILED] Can't resolve 'node:fs' in 'E:\Work\Code\sources\flex-tools\src\package'


Error
    at warpErrors (E:\Work\Code\sources\flex-tools\node_modules\.pnpm\@modern-js+libuild@0.11.6\node_modules\@modern-js\libuild\dist\index.js:57891:17)
    at Libuilder.getErrors (E:\Work\Code\sources\flex-tools\node_modules\.pnpm\@modern-js+libuild@0.11.6\node_modules\@modern-js\libuild\dist\index.js:60973:12)
    at Libuilder.build (E:\Work\Code\sources\flex-tools\node_modules\.pnpm\@modern-js+libuild@0.11.6\node_modules\@modern-js\libuild\dist\index.js:60895:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at E:\Work\Code\sources\flex-tools\node_modules\.pnpm\@modern-js+module-tools@2.10.0_typescript@5.1.3\node_modules\@modern-js\module-tools\dist\builder\index.js:84:15
    at Generator.next (<anonymous>)
    at fulfilled (E:\Work\Code\sources\flex-tools\node_modules\.pnpm\@modern-js+module-tools@2.10.0_typescript@5.1.3\node_modules\@modern-js\module-tools\dist\builder\index.js:32:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ELIFECYCLE  Command failed with exit code 1.

```

### 复现链接

https://github.com/zhangfisher/flex-tools

### 复现步骤

https://github.com/zhangfisher/flex-tools

**Comment by chenjiahan** [comment]
请问是在哪个分支上复现这个问题呢，我在 master 分支 build 试了下，没有出现上述异常

![image](https://github.com/web-infra-dev/modern.js/assets/7237365/2bc9a29b-36f7-44ec-a8ee-3b80e2730194)

**Comment by zhangfisher** [comment]
出问题的我还没有提交，现在提交了，在master分支

**Comment by 10Derozan** [comment]
升级一下版本就行了

**Comment by chenjiahan** [comment]
可以执行 npx modern upgrade 升级试一下哈

**Comment by zhangfisher** [comment]
升级到`"@modern-js/module-tools": "^2.22.1",`后解决

配置方式是否有升级？

以下是tsup的配置

```
export default defineConfig({
    entry: [
        'src/**/*.ts'
    ],
    format: ['esm','cjs'],
    dts: true,
    splitting: true,
    sourcemap: false,
    clean: true,
    treeshake:true,  
    minify: true
}) 
```

而对比一个modern-tools的配置则复杂则多，需要写一个插件来配置支持

**Comment by chenjiahan** [comment]
> 而对比一个modern-tools的配置则复杂则多，需要写一个插件来配置支持

插件是为了解决什么问题嘞

**Comment by zhangfisher** [comment]
```

const ModulePlugin = (): CliPlugin<ModuleTools> => ({
  name: 'module',
  setup: () => ({
    modifyLibuild(config) {
      config.esbuildOptions = c => {
        c.banner = esbuildOptions.banner;
        c.plugins?.push(...esbuildOptions.plugins);
        c.entryNames = '[dir]/[name]'
        c.chunkNames = '[name]-[hash]';
        if (config.format === 'esm') {
          c.outExtension = { '.js': '.mjs' }
        }
        return c;
      };
      return config;
    },
  }),
});

```


解决在同一个文件夹下输出`.js`,`.cjs`,`.mjs`的问题

**Comment by chenjiahan** [comment]
.mjs 和 .cjs 确实需要 Module Tools 提供内置的支持，通过插件解决属于过渡方案
