### ISSUE TITLE
[Bug]: Modern.js Doc may have problems in the window system

### ISSUE THREAD

**Issue by kainonly** [web-infra-dev/modern.js#4088]
### Version

```sh
System:
  OS: Windows 10 10.0.19045
  CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
  Memory: 20.67 GB / 31.93 GB
Browsers:
  Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.58)
  Internet Explorer: 11.0.19041.1566
npmPackages:
  @modern-js/doc-tools: 2.24.1 => 2.24.1
```

### Details

I tried this nice project for the first time, when I follow the quick start guide, I encounter some errors in the window system, but everything works fine under macos

```
App.tsx:40 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toc')
    at App.tsx:40:1
    at step (tslib.es6.mjs:147:1)
    at Object.next (tslib.es6.mjs:128:1)
    at asyncGeneratorStep (_async_to_generator.js:3:1)
    at _next (_async_to_generator.js:20:1)
```

![image](https://github.com/web-infra-dev/modern.js/assets/9986159/13494809-0547-4315-96da-ff8bf601fa4a)

### Reproduce link

https://modernjs.dev/doc-tools/guide/start/getting-started.html

### Reproduce Steps

Method 1: Create via CLI

```shell
npx @modern-js/create@latest modern-doc-app

? 请选择你想创建的工程类型 文档站
? 请选择包管理工具 pnpm
 WARN  deprecated hast@1.0.0: Renamed to rehype
Packages: +857
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are copied from the content-addressable store to the virtual store.
  Content-addressable store is at: D:\.pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 889, reused 852, downloaded 0, added 857, done

dependencies:
+ @modern-js/doc-tools 2.24.1
+ tailwindcss 3.2.7 (3.3.2 is available)

devDependencies:
+ @types/node 16.18.16 (20.3.2 is available)
+ typescript 5.0.4 (5.1.6 is available)

Done in 14.9s
[INFO] 依赖自动安装成功
[WARN] git 仓库初始化失败， 请确认是否安装 git 且初始化 git username 和 email
[INFO] 创建成功！
可在新项目的目录下运行以下命令：
pnpm run dev          # 启动开发服务器
pnpm run build        # 构建生产环境产物
pnpm run serve        # 在本地预览生产版本
[INFO] 你可以执行 'cd modern-doc-app' 进入目录
```

dev is normal

```shell
> modern-doc-app@0.1.0 dev D:\workspace\modern-doc-app
> modern dev

info    Starting dev server...
info    Extracting site data...
info    Dev server running at:        

  > Network:  http://192.168.3.2:8080/
  > Local:    http://localhost:8080/  

Client ████████████████████████████████████████ 100% done
Success Client compiled successfully in 1452 ms
```

**Comment by chenjiahan** [comment]
I think this bug should be fixed in the new version today, you can try the new version after we release it: https://github.com/web-infra-dev/modern.js/pull/4086

**Comment by kainonly** [comment]
> I think this bug should be fixed in the new version today, you can try the new version after we release it: #4086

OK, thanks

**Comment by chenjiahan** [comment]
@kainonly Please try the new version: v2.25.0

**Comment by kainonly** [comment]
> @kainonly Please try the new version: v2.25.0

No problem, now it works fine
