### ISSUE TITLE
[Bug]: bundleless DTS failed:No inputs were found in config file

### ISSUE THREAD

**Issue by zhangfisher** [web-infra-dev/modern.js#4655]
### Version

```sh
System: Windows

@modern-js/module-tools :  2.35.0
```

### Details

使用`@modern-js/module-tools`构建时出错

同样的配置使用`tsup`构建成功

错误信息发下：
 
```
modern build && cd dist && npm pkg set main=index.js && npm pkg set module=index.mjs && npm pkg set types=index.d.ts

  Modern.js Module v2.35.0

error   ModuleBuildError: 

bundleless DTS failed:

error TS18003: No inputs were found in config file 'E:/Work/Code/sources/flex-tools/node_modules/.dts-temp/DFDrTI2VnLBT14ehAEo8e/tsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '["E:\\Work\\Code\\sources\\flex-tools\\node_modules\\.dts-temp\\DFDrTI2VnLBT14ehAEo8e\\src"]'.


Found 1 error.

    at makeError (E:\Work\Code\sources\flex-tools\node_modules\.pnpm\@modern-js+utils@2.35.0_react-dom@18.2.0_react@18.2.0\node_modules\@modern-js\utils\dist\compiled\execa\index.js:1:8677)
    at handlePromise (E:\Work\Code\sources\flex-tools\node_modules\.pnpm\@modern-js+utils@2.35.0_react-dom@18.2.0_react@18.2.0\node_modules\@modern-js\utils\dist\compiled\execa\index.js:1:5315)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generatorDts (E:\Work\Code\sources\flex-tools\node_modules\.pnpm\@modern-js+module-tools@2.35.0_react-dom@18.2.0_react@18.2.0_typescript@5.2.2\node_modules\@modern-js\module-tools\dist\builder\dts\tsc.js:69:5)
    at async runTsc (E:\Work\Code\sources\flex-tools\node_modules\.pnpm\@modern-js+module-tools@2.35.0_react-dom@18.2.0_react@18.2.0_typescript@5.2.2\node_modules\@modern-js\module-tools\dist\builder\dts\tsc.js:82:18)
    at async generatorDts (E:\Work\Code\sources\flex-tools\node_modules\.pnpm\@modern-js+module-tools@2.35.0_react-dom@18.2.0_react@18.2.0_typescript@5.2.2\node_modules\@modern-js\module-tools\dist\builder\build.js:103:5)
    at async E:\Work\Code\sources\flex-tools\node_modules\.pnpm\@modern-js+module-tools@2.35.0_react-dom@18.2.0_react@18.2.0_typescript@5.2.2\node_modules\@modern-js\module-tools\dist\builder\build.js:66:7
    at async E:\Work\Code\sources\flex-tools\node_modules\.pnpm\@modern-js+module-tools@2.35.0_react-dom@18.2.0_react@18.2.0_typescript@5.2.2\node_modules\@modern-js\module-tools\compiled\p-map\index.js:1:2587
    at Object.run (E:\Work\Code\sources\flex-tools\node_modules\.pnpm\@modern-js+module-tools@2.35.0_react-dom@18.2.0_react@18.2.0_typescript@5.2.2\node_modules\@modern-js\module-tools\dist\builder\index.js:51:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async build (E:\Work\Code\sources\flex-tools\node_modules\.pnpm\@modern-js+module-tools@2.35.0_react-dom@18.2.0_react@18.2.0_typescript@5.2.2\node_modules\@modern-js\module-tools\dist\build.js:29:3)
    at async Command.<anonymous> (E:\Work\Code\sources\flex-tools\node_modules\.pnpm\@modern-js+module-tools@2.35.0_react-dom@18.2.0_react@18.2.0_typescript@5.2.2\node_modules\@modern-js\module-tools\dist\command.js:33:5)
 ELIFECYCLE  Command failed with exit code 1.

```

### Reproduce link

https://github.com/zhangfisher/flex-tools

### Reproduce Steps

1. git clone https://github.com/zhangfisher/flex-tools
2. pnpm build     // 默认构建使用@modern-js/module-tools失败
3. pnpm build:tsup     // 成功

**Comment by zhangfisher** [comment]
好象是在生成`dts`时出错了，但是为什么是缺少`/.dts-temp/DFDrTI2VnLBT14ehAEo8e/tsconfig.json'`，是自己生成的临时配置文件？

**Comment by chenjiahan** [comment]
对的，Modern.js Module 会在 node_modules 下面生成一个临时的 tsconfig 文件，并注入一些默认配置（tsup 应该没有这个行为，所以不会有问题）

你需要在根目录的 tsconfig.json 里配置 "include"，否则 tsc 编译的时候会无法识别源代码：

```json
{
  "include": ["src"],
}
```

**Comment by chenjiahan** [comment]
@10Derozan 如果用户没有指定 include，我们可以考虑默认注入一个 `"include": ["src"]` 配置

**Comment by zhangfisher** [comment]
之前版本是没问题，直到某次更新后才出现这个问题的，算兼容性问题吧？

编译是可以的，只是无法生成`.d.ts`

建议默认注入一个 `"include": ["src"]` 配置

**Comment by chenjiahan** [comment]
嗯，我们会再跟进一下这个问题

**Comment by zhangfisher** [comment]
这个问题在 2.40.0还没有解决

```
error   ModuleBuildError: 

bundleless DTS failed:

error TS18003: No inputs were found in config file 'E:/Work/Code/sources/flex-tools/node_modules/.dts-temp/yYiP6KRlNTl7eOuCuR3v4/tsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '["E:\\Work\\Code\\sources\\flex-tools\\node_modules\\.dts-temp\\yYiP6KRlNTl7eOuCuR3v4\\src"]'.

```

**Comment by 10Derozan** [comment]
现在我们不再会开辟新的 temp 目录跑 tsc了，现在会完全遵循用户 tsconfig，这个错误将不再出现。
对于 tsc 来说，input 默认为项目里的所有文件。

**Comment by zhangfisher** [comment]
👍
