### ISSUE TITLE
[Bug]: win10下, 启用可选功能, 启动Storybook V7 出错

### ISSUE THREAD

**Issue by wangjue666** [web-infra-dev/modern.js#5477]
### 版本信息

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 5.52 GB / 15.95 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (119.0.2151.72)
    Internet Explorer: 11.0.19041.1566
```

### 问题详情

![image](https://github.com/web-infra-dev/modern.js/assets/24707417/243f389f-7ede-4c15-9128-a07c41fc442a)

```
λ  pnpm run storybook

> myapp@0.1.0 storybook E:\test\myapp
> storybook dev -p 6006

@storybook/cli v7.6.17

SB_CORE-COMMON_0003 (CouldNotEvaluateFrameworkError): Could not evaluate the '@modern-js/storybook' package from the 'framework' field of Storybook config.

Are you sure it's a valid package and is installed?
    at validateFrameworkName (.\node_modules\.pnpm\@storybook+core-common@7.6.17\node_modules\@storybook\core-common\dist\index.js:21:4479)
    at buildDevStandalone (.\node_modules\.pnpm\@storybook+core-server@7.6.17\node_modules\@storybook\core-server\dist\index.js:119:1432)
    at async withTelemetry (.\node_modules\.pnpm\@storybook+core-server@7.6.17\node_modules\@storybook\core-server\dist\index.js:65:3948)
    at async dev (.\node_modules\.pnpm\@storybook+cli@7.6.17\node_modules\@storybook\cli\dist\generate.js:514:401)
    at async Command.<anonymous> (.\node_modules\.pnpm\@storybook+cli@7.6.17\node_modules\@storybook\cli\dist\generate.js:529:225)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

× Would you like to help improve Storybook by sending anonymous crash reports? ... yes

```

### 复现链接

无

### 复现步骤

```

npx @modern-js/create@latest myapp

? 请选择你想创建的工程类型 Npm 模块
- Load Generator...(node:16268) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
? 请填写项目名称 myapp
? 请选择开发语言 TS
? 请选择包管理工具 pnpm

cd myapp

pnpm run new

> modern new

  Modern.js Module v2.47.1

? 请选择你想要的操作 启用可选功能
? 请选择功能名称 启用「Storybook」V7


pnpm run storybook
```

参考文档 https://modernjs.dev/module-tools/guide/basic/using-storybook.html

**Comment by kirainmoe** [comment]
This could be reproduced on Windows. 

But I thought that it was a problem of storybook itself, because it was resolving third-party framework preset (i.e. frameworks not in its official whitelist) with a form like require.resolve(path.join(frameworkName, “presets”)). On Windows it will resolve  @modern-js\storybook\presets and throw an error. 

A possible solution is to run storybook under WSL.

**Comment by wangjue666** [comment]
> <img alt="image" width="520" src="https://private-user-images.githubusercontent.com/22373761/309730608-8cda5c4e-2515-47f1-89df-fdab6d5c683d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MDI0MjMsIm5iZiI6MTcwOTYwMjEyMywicGF0aCI6Ii8yMjM3Mzc2MS8zMDk3MzA2MDgtOGNkYTVjNGUtMjUxNS00N2YxLTg5ZGYtZmRhYjZkNWM2ODNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDAxMjg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZjgzMzBjOGU4Y2M0ZjBmOTM1OTFiNWY0MDhmMWIwYThlYjA2YjNlNTM4M2MyMDY4MzdlOTA5NTk1ZjBkMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.usZgbuz3TPB3An1u23Yk2RG-LNU_3bI7TteeGLhG9JI">
> Did you see the above success words or get an error when executing run new?
> 
> By the way, I have not reproduced this problem in modern.js 2.48.0. You can try upgrading to the latest version.


@9aoy  刚刚重试试了下,是2.48.0版本还是不可以，我的是window10系统

![image](https://github.com/web-infra-dev/modern.js/assets/24707417/8dd61d61-988b-4d25-acc0-da9d4b45cb67)

**Comment by wangjue666** [comment]
> This could be reproduced on Windows.
> 
> But I thought that it was a problem of storybook itself, because it was resolving third-party framework preset (i.e. frameworks not in its official whitelist) with a form like require.resolve(path.join(frameworkName, “presets”)). On Windows it will resolve @modern-js\storybook\presets and throw an error.
> 
> A possible solution is to run storybook under WSL.

哥，能否使用 patch-package 这样的工具进行修改下storybook的白名单？好在windows上进行使用

**Comment by 10Derozan** [comment]
Can you provide a repo? Maybe the reason is that you have not installed `@modern-js/storybook`?

**Comment by wangjue666** [comment]
> Can you provide a repo? Maybe the reason is that you have not installed `@modern-js/storybook`?

@10Derozan  I am confident that I have installed it. here is  repo, https://github.com/wangjue666/myapp

![image](https://github.com/web-infra-dev/modern.js/assets/24707417/7836f5b3-d2d4-4eb4-abfd-3b640f2df0fb)

**Comment by h7ml** [comment]
Encountered the same problem with log information
```bash
> calendar@0.1.0 storybook \calendar
> storybook dev -p 6006

@storybook/cli v7.6.17

(node:23596) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
SB_CORE-COMMON_0003 (CouldNotEvaluateFrameworkError): Could not evaluate the '@modern-js/storybook' package from the 'framework' field of Storybook config.

Are you sure it's a valid package and is installed?
    at validateFrameworkName (.\node_modules\.pnpm\@storybook+core-common@7.6.17\node_modules\@storybook\core-common\dist\index.js:21:4479)
    at buildDevStandalone (.\node_modules\.pnpm\@storybook+core-server@7.6.17\node_modules\@storybook\core-server\dist\index.js:119:1432)
    at async withTelemetry (.\node_modules\.pnpm\@storybook+core-server@7.6.17\node_modules\@storybook\core-server\dist\index.js:65:3948)
    at async dev (.\node_modules\.pnpm\@storybook+cli@7.6.17\node_modules\@storybook\cli\dist\generate.js:514:401)
    at async Command.<anonymous> (.\node_modules\.pnpm\@storybook+cli@7.6.17\node_modules\@storybook\cli\dist\generate.js:529:225)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by elevenwangyang** [comment]
遇到一样的问题了，请问解决了吗？

**Comment by zllkjc** [comment]
Modern.js Module 现在已经升级为 rslib，这个问题在 rslib 中得到了很好的解决，参考 https://lib.rsbuild.dev/zh/guide/advanced/storybook
