### ISSUE TITLE
[Bug]: babel相关api无法在ssr端运行

### ISSUE THREAD

**Issue by ghost** [web-infra-dev/modern.js#5564]
### 版本信息

```sh
System:
    OS: macOS 14.1.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 22.23 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 17.1.2
  npmPackages:
    @modern-js/app-tools: 2.48.3 => 2.48.3 
    @modern-js/eslint-config: 2.48.3 => 2.48.3 
    @modern-js/runtime: 2.48.3 => 2.48.3 
    @modern-js/tsconfig: 2.48.3 => 2.48.3
```

### 问题详情

Web Server Error - Internal server error, error = Error: Cannot find module '@babel/parser'
    at webpackMissingModule (/Volumes/works/tmp/modern-demo/dist/bundles/main-server-loaders.js:56657:50)
    at Module../src/babel.server.js (/Volumes/works/tmp/modern-demo/dist/bundles/main-server-loaders.js:56657:138)
    at __webpack_require__ (/Volumes/works/tmp/modern-demo/dist/bundles/main-server-loaders.js:64544:37)
    at Module../src/routes/page.data.ts (/Volumes/works/tmp/modern-demo/dist/bundles/main-server-loaders.js:46534:70)
    at __webpack_require__ (/Volumes/works/tmp/modern-demo/dist/bundles/main-server-loaders.js:64544:37)
    at Module../node_modules/.modern-js/main/route-server-loaders.js (/Volumes/works/tmp/modern-demo/dist/bundles/main-server-loaders.js:46496:88)
    at __webpack_require__ (/Volumes/works/tmp/modern-demo/dist/bundles/main-server-loaders.js:64544:37)
    at Module../node_modules/.modern-js/main/server-loader-combined.js (/Volumes/works/tmp/modern-demo/dist/bundles/main-server-loaders.js:46523:139)
    at __webpack_require__ (/Volumes/works/tmp/modern-demo/dist/bundles/main-server-loaders.js:64544:37)
    at /Volumes/works/tmp/modern-demo/dist/bundles/main-server-loaders.js:64618:27
    at Object.<anonymous> (/Volumes/works/tmp/modern-demo/dist/bundles/main-server-loaders.js:64620:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)

### 复现链接

https://github.com/aasychen/modern-demo.git

### 复现步骤

1.pnpm i @babel/parser 安装babel包 
1.开启modern 配置 { server:{ ssr: true } }
2.使用babel相关api在服务端使用，babel被拦截，import parser from ’@babel/parser‘ parser为undefined

**Comment by yimingjfe** [comment]
因为项目中没有安装 @babel/parser，我安装了最新版的 @babel/parser，@babel/parser 是没有 default export，你是不是需要使用 `parse` 函数？

**Comment by aasychen** [comment]
> 因为项目中没有安装 @babel/parser，我安装了最新版的 @babel/parser，@babel/parser 是没有 default export，你是不是需要使用 `parse` 函数？

是的，我要在运行时使用babel相关工具库，所以我通过前端发送到字符串到都服务端解析。

**Comment by yimingjfe** [comment]
这里应该是项目中使用 `babel/parser` 的问题，与框架无关，改变 import 方式后，应该就可以了
