### ISSUE TITLE
[Bug]: Unable to enable tailwindcss

### ISSUE THREAD

**Issue by raolak** [web-infra-dev/modern.js#5833]
Require stack:
- /private/var/folders/9r/tzyxp_y13sd50l2gbmbgpm140000gn/T/csmith-generator/@modern-js/tailwindcss-generator@3.4.0/node_modules/.pnpm/caniuse-lite@1.0.30001634/node_modules/caniuse-lite/dist/unpacker/feature.js
- /private/var/folders/9r/tzyxp_y13sd50l2gbmbgpm140000gn/T/csmith-generator/@modern-js/tailwindcss-generator@3.4.0/node_modules/.pnpm/@modern-js+utils@2.53.0/node_modules/@modern-js/utils/dist/compiled/browserslist/index.js
- /private/var/folders/9r/tzyxp_y13sd50l2gbmbgpm140000gn/T/csmith-generator/@modern-js/tailwindcss-generator@3.4.0/node_modules/.pnpm/@modern-js+utils@2.53.0/node_modules/@modern-js/utils/dist/cjs/compiled.js
- /private/var/folders/9r/tzyxp_y13sd50l2gbmbgpm140000gn/T/csmith-generator/@modern-js/tailwindcss-generator@3.4.0/node_modules/.pnpm/@modern-js+utils@2.53.0/node_modules/@modern-js/utils/dist/cjs/index.js
- /private/var/folders/9r/tzyxp_y13sd50l2gbmbgpm140000gn/T/csmith-generator/@modern-js/tailwindcss-generator@3.4.0/dist/index.js
- /Users/[your_username]/.npm/_npx/233f814a22d5c72b/node_modules/@modern-js/codesmith/dist/cjs/utils/nodeRequire.js
- /Users/[your_username]/.npm/_npx/233f814a22d5c72b/node_modules/@modern-js/codesmith/dist/cjs/generator/index.js
- /Users/[your_username]/.npm/_npx/233f814a22d5c72b/node_modules/@modern-js/codesmith/dist/cjs/codesmith/index.js
- /Users/[your_username]/.npm/_npx/233f814a22d5c72b/node_modules/@modern-js/codesmith/dist/cjs/index.js
- /Users/[your_username]/.npm/_npx/233f814a22d5c72b/node_modules/@modern-js/new-action/dist/cjs/mwa.js
- /Users/[your_username]/.npm/_npx/233f814a22d5c72b/node_modules/@modern-js/new-action/dist/cjs/run.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/private/var/folders/9r/tzyxp_y13sd50l2gbmbgpm140000gn/T/csmith-generator/@modern-js/tailwindcss-generator@3.4.0/node_modules/.pnpm/caniuse-lite@1.0.30001634/node_modules/caniuse-lite/dist/unpacker/feature.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/private/var/folders/9r/tzyxp_y13sd50l2gbmbgpm140000gn/T/csmith-generator/@modern-js/tailwindcss-generator@3.4.0/node_modules/.pnpm/caniuse-lite@1.0.30001634/node_modules/caniuse-lite/dist/unpacker/feature.js',
    '/private/var/folders/9r/tzyxp_y13sd50l2gbmbgpm140000gn/T/csmith-generator/@modern-js/tailwindcss-generator@3.4.0/node_modules/.pnpm/@modern-js+utils@2.53.0/node_modules/@modern-js/utils/dist/compiled/browserslist/index.js',
    '/private/var/folders/9r/tzyxp_y13sd50l2gbmbgpm140000gn/T/csmith-generator/@modern-js/tailwindcss-generator@3.4.0/node_modules/.pnpm/@modern-js+utils@2.53.0/node_modules/@modern-js/utils/dist/cjs/compiled.js',
    '/private/var/folders/9r/tzyxp_y13sd50l2gbmbgpm140000gn/T/csmith-generator/@modern-js/tailwindcss-generator@3.4.0/node_modules/.pnpm/@modern-js+utils@2.53.0/node_modules/@modern-js/utils/dist/cjs/index.js',
    '/private/var/folders/9r/tzyxp_y13sd50l2gbmbgpm140000gn/T/csmith-generator/@modern-js/tailwindcss-generator@3.4.0/dist/index.js',
    '/Users/[your_username]/.npm/_npx/233f814a22d5c72b/node_modules/@modern-js/codesmith/dist/cjs/utils/nodeRequire.js',
    '/Users/[your_username]/.npm/_npx/233f814a22d5c72b/node_modules/@modern-js/codesmith/dist/cjs/generator/index.js',
    '/Users/[your_username]/.npm/_npx/233f814a22d5c72b/node_modules/@modern-js/codesmith/dist/cjs/codesmith/index.js',
    '/Users/[your_username]/.npm/_npx/233f814a22d5c72b/node_modules/@modern-js/codesmith/dist/cjs/index.js',
    '/Users/[your_username]/.npm/_npx/233f814a22d5c72b/node_modules/@modern-js/new-action/dist/cjs/mwa.js',
    '/Users/[your_username]/.npm/_npx/233f814a22d5c72b/node_modules/@modern-js/new-action/dist/cjs/run.js'
  ]
}
/Users/[your_username]/.npm/_npx/233f814a22d5c72b/node_modules/@modern-js/codesmith/dist/cjs/codesmith/index.js:57
      throw new Error("run task error");
            ^

Error: run task error
    at CodeSmith.forge (/Users/[your_username]/.npm/_npx/233f814a22d5c72b/node_modules/@modern-js/codesmith/dist/cjs/codesmith/index.js:57:13)
    at async MWANewAction (/Users/[your_username]/.npm/_npx/233f814a22d5c72b/node_modules/@modern-js/new-action/dist/cjs/mwa.js:117:3)

Node.js v18.20.3
error   Error: Command failed with exit code 1: npx --yes @modern-js/new-action@2.53.0 --config={"debug":false,"needInstall":true,"locale":"en"} --solution=mwa

**Comment by raolak** [comment]
resolved !
