### ISSUE TITLE
[Bug]: 根据文档操作微前端运行失败

### ISSUE THREAD

**Issue by xmsz-stu** [web-infra-dev/modern.js#6113]
### 版本信息

```sh
System:
    OS: macOS 14.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 23.66 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 127.0.6533.120
    Edge: 97.0.1072.69
    Safari: 17.6
    Safari Technology Preview: 18.0
  npmPackages:
    @modern-js/app-tools: 2.58.2 => 2.58.2 
    @modern-js/eslint-config: 2.58.2 => 2.58.2 
    @modern-js/plugin-garfish: 2.58.2 => 2.58.2 
    @modern-js/runtime: 2.58.2 => 2.58.2 
    @modern-js/tsconfig: 2.58.2 => 2.58.2
```

### 问题详情

根据https://modernjs.dev/guides/topic-detail/micro-frontend/c02-development.html文档操作
然后各自应用都能运行，但是在主应用里加载子应用时无法加载，提示
```
Unexpected Application Error!
Cannot use 'in' operator to search for 'default' in null
TypeError: Cannot use 'in' operator to search for 'default' in null
    at lazyInitializer (http://localhost:8081/static/js/lib-react.js:34647:23)
    at mountLazyComponent (http://localhost:8081/static/js/lib-react.js:19946:19)
    at beginWork (http://localhost:8081/static/js/lib-react.js:21595:16)
    at beginWork$1 (http://localhost:8081/static/js/lib-react.js:27428:14)
    at performUnitOfWork (http://localhost:8081/static/js/lib-react.js:26559:12)
    at workLoopSync (http://localhost:8081/static/js/lib-react.js:26468:5)
    at renderRootSync (http://localhost:8081/static/js/lib-react.js:26436:7)
    at recoverFromConcurrentError (http://localhost:8081/static/js/lib-react.js:25852:20)
    at performConcurrentWorkOnRoot (http://localhost:8081/static/js/lib-react.js:25752:22)
    at workLoop (http://localhost:8081/static/js/lib-react.js:36296:34)
```

### 复现链接

https://github.com/xmsz/demo-20240822.git

### 复现步骤

各个目录pnpm i , pnpm run dev
打开8080
点击跳转到子应用

**Comment by caohuilin** [comment]
![image](https://github.com/user-attachments/assets/c82b85a6-0d44-4587-911a-071d0ae4152f)
按照复现步骤试了一下，没报错
