### ISSUE TITLE
[Bug]: npx @modern-js/create@latest TypeError: Invalid URL

### ISSUE THREAD

**Issue by xxnuo** [web-infra-dev/modern.js#6426]
### 版本信息

  System:
    OS: macOS 14.5
    Memory: 32.71 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh

### 问题详情

```bash
pnpx @modern-js/create@latest
🏃  Load Generator...node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

TypeError: Invalid URL
    at new URL (node:internal/url:806:29)
    at /Users/xxnuo/Library/Caches/pnpm/dlx/5epputrg6ueaxxpol77p6rvhfq/192b9d85315-1151a/node_modules/.pnpm/@modern-js+create@2.60.4/node_modules/@modern-js/create/dist/index.js:43795:22
    at Generator.next (<anonymous>)
    at /Users/xxnuo/Library/Caches/pnpm/dlx/5epputrg6ueaxxpol77p6rvhfq/192b9d85315-1151a/node_modules/.pnpm/@modern-js+create@2.60.4/node_modules/@modern-js/create/dist/index.js:75:61
    at new Promise (<anonymous>)
    at __async (/Users/xxnuo/Library/Caches/pnpm/dlx/5epputrg6ueaxxpol77p6rvhfq/192b9d85315-1151a/node_modules/.pnpm/@modern-js+create@2.60.4/node_modules/@modern-js/create/dist/index.js:59:10)
    at dispatchHttpRequest (/Users/xxnuo/Library/Caches/pnpm/dlx/5epputrg6ueaxxpol77p6rvhfq/192b9d85315-1151a/node_modules/.pnpm/@modern-js+create@2.60.4/node_modules/@modern-js/create/dist/index.js:43748:12)
    at /Users/xxnuo/Library/Caches/pnpm/dlx/5epputrg6ueaxxpol77p6rvhfq/192b9d85315-1151a/node_modules/.pnpm/@modern-js+create@2.60.4/node_modules/@modern-js/create/dist/index.js:43733:5
    at new Promise (<anonymous>)
    at wrapAsync (/Users/xxnuo/Library/Caches/pnpm/dlx/5epputrg6ueaxxpol77p6rvhfq/192b9d85315-1151a/node_modules/.pnpm/@modern-js+create@2.60.4/node_modules/@modern-js/create/dist/index.js:43716:10)
    at Axios.<anonymous> (/Users/xxnuo/Library/Caches/pnpm/dlx/5epputrg6ueaxxpol77p6rvhfq/192b9d85315-1151a/node_modules/.pnpm/@modern-js+create@2.60.4/node_modules/@modern-js/create/dist/index.js:44952:43)
    at Generator.throw (<anonymous>)
    at rejected (/Users/xxnuo/Library/Caches/pnpm/dlx/5epputrg6ueaxxpol77p6rvhfq/192b9d85315-1151a/node_modules/.pnpm/@modern-js+create@2.60.4/node_modules/@modern-js/create/dist/index.js:69:29) {
  code: 'ERR_INVALID_URL',
  input: '/@modern-js/codesmith-global/-/codesmith-global-2.6.5.tgz'
}

Node.js v20.18.0

npx @modern-js/create@latest
Need to install the following packages:
@modern-js/create@2.60.4
Ok to proceed? (y)

🏃  Load Generator...node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

TypeError: Invalid URL
    at new URL (node:internal/url:806:29)
    at /Users/xxnuo/.npm/_npx/c3b7a16190ec2c47/node_modules/@modern-js/create/dist/index.js:43795:22
    at Generator.next (<anonymous>)
    at /Users/xxnuo/.npm/_npx/c3b7a16190ec2c47/node_modules/@modern-js/create/dist/index.js:75:61
    at new Promise (<anonymous>)
    at __async (/Users/xxnuo/.npm/_npx/c3b7a16190ec2c47/node_modules/@modern-js/create/dist/index.js:59:10)
    at dispatchHttpRequest (/Users/xxnuo/.npm/_npx/c3b7a16190ec2c47/node_modules/@modern-js/create/dist/index.js:43748:12)
    at /Users/xxnuo/.npm/_npx/c3b7a16190ec2c47/node_modules/@modern-js/create/dist/index.js:43733:5
    at new Promise (<anonymous>)
    at wrapAsync (/Users/xxnuo/.npm/_npx/c3b7a16190ec2c47/node_modules/@modern-js/create/dist/index.js:43716:10)
    at Axios.<anonymous> (/Users/xxnuo/.npm/_npx/c3b7a16190ec2c47/node_modules/@modern-js/create/dist/index.js:44952:43)
    at Generator.throw (<anonymous>)
    at rejected (/Users/xxnuo/.npm/_npx/c3b7a16190ec2c47/node_modules/@modern-js/create/dist/index.js:69:29) {
  code: 'ERR_INVALID_URL',
  input: '/@modern-js/repo-generator/-/repo-generator-3.7.0.tgz'
}

Node.js v20.18.0
```

### 复现链接

No

### 复现步骤

`pnpx @modern-js/create@latest`
or
`npx @modern-js/create@latest`

**Comment by xxnuo** [comment]
原来是因为用了 huawei Huawei Cloud https://mirrors.huaweicloud.com/repository/npm/ 华为开源镜像站源，换了tencent 的正常了
