### ISSUE TITLE
[Bug]: Error [ Federation Runtime ]: [ Federation Runtime ]: The attribute remoteEntry of tasks must not be undefined.

### ISSUE THREAD

**Issue by VictorPulzz** [web-infra-dev/modern.js#6647]
### Version

```sh
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 59.31 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 131.0.6778.141
    Safari: 17.0
```

### Details

Hello dear devs!
I was planning to do it this way:
I have a host application modern.js
And there are some microfronts built on rsbuild.
And I wanted to connect them to each other.
Here is my config for rsbuild (just standard as from documentation + module federation)

**rsbuild.config.ts**
```ts
import {defineConfig} from '@rsbuild/core';
import {pluginReact} from '@rsbuild/plugin-react';
import {pluginSass} from '@rsbuild/plugin-sass';
import {pluginModuleFederation} from "@module-federation/rsbuild-plugin";

export default defineConfig({
  plugins: [
    pluginReact(),
    pluginSass(),
    pluginModuleFederation({
      name: 'tasks',
      manifest: true,
      filename: 'remoteEntry.js',
      exposes: {
        './App': './src/App.tsx',
      },
      shared: {
        react: {
          singleton: true,
          requiredVersion: "^18.0.0",
        },
        "react-dom": {
          singleton: true,
          requiredVersion: "^18.0.0",
        },
      },
    }),
  ],
  server: {
    port: 3051
  },
});

```
And installed basic modern.js and configured module federation from documentation
configs:
**modern.config.ts:** 
```ts

import {appTools, defineConfig} from '@modern-js/app-tools';
import {config} from './main.config'
import { moduleFederationPlugin } from '@module-federation/modern-js';
import { tailwindcssPlugin } from '@modern-js/plugin-tailwindcss'

export default defineConfig(({env}) => ({
  dev: {
    port: env === 'development' ? config.devPort : config.prodPort,
  },
  runtime: {
    router: true,
  },
  server: {
    ssr: {
      mode: 'stream',
    },
  },
  output: {
    distPath: {
      // root: platformPathBuild('app')
    }
  },
  plugins: [
    appTools({
      bundler: 'rspack',
    }),
    tailwindcssPlugin(),
    moduleFederationPlugin(),
  ],
}));
```
**module-federation.config.ts:** 
```ts
import { createModuleFederationConfig } from '@module-federation/modern-js';

export default createModuleFederationConfig({
  name: 'app',
  remotes: {
    tasks: 'tasks@http://localhost:3051/mf-manifest.json',
  },
  shared: {
    react: {
      singleton: true,
      requiredVersion: "^18.0.0",
    },
    "react-dom": {
      singleton: true,
      requiredVersion: "^18.0.0",
    },
  },
});
```

### Reproduce link

https://github.com/VictorPulzz/modernjs-rsbuuld-modulefederation

### Reproduce Steps

1. cd app && npm i && cd ../tasks && npm i && cd ..
2. cd app && npm run dev && cd ../tasks && npm run dev && cd ..

**Comment by VictorPulzz** [comment]
Error text:
`
[ Module Federation Dev Server ] Error [ Federation Runtime ]: [ Federation Runtime ]: The attribute remoteEntry of tasks must not be undefined.
  at Object.error (/modernjs-rsbuuld-modulefederation/app/node_modules/@module-federation/runtime/dist/share.cjs.js:25:1)
at assignRemoteInfo (/modernjs-rsbuuld-modulefederation/app/node_modules/@module-federation/runtime/dist/index.cjs.js:747:1)
at Array.afterResolve (/modernjs-rsbuuld-modulefederation/app/node_modules/@module-federation/runtime/dist/index.cjs.js:766:1)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at RemoteHandler.getRemoteModuleAndOptions (/modernjs-rsbuuld-modulefederation/app/node_modules/@module-federation/runtime/dist/index.cjs.js:1723:1)
at initRemoteModule (/modernjs-rsbuuld-modulefederation/app/node_modules/@module-federation/runtime/dist/index.cjs.js:1378:1)
at async Promise.all (index 0)
at /modernjs-rsbuuld-modulefederation/app/node_modules/@module-federation/runtime/dist/index.cjs.js:1251:1
at async Promise.all (index 0)
at SharedHandler.loadShare (/modernjs-rsbuuld-modulefederation/app/node_modules/@module-federation/runtime/dist/index.cjs.js:1250:1)
[ Module Federation Dev Server ] Error Process(54791) unhandledRejection, mf server will exit...

Process finished with exit code 1
`

**Comment by zllkjc** [comment]
Sorry for miss this issue. This issue is cause by enable Modern.js SSR, but the remotes not support SSR.

In ths past, `@module-federation/modern-js` will read the modern.config.js, and if `server.ssr` is true, the plugin also need remotes has SSR products. Now the plugin support a new config `ssr: false`, which you can see https://github.com/module-federation/core/blob/main/packages/modernjs/src/types/index.ts#L8.

After add this config, the error will disappear, but you still need load remote in client.

BTW, there is still some problem in Module Federation with Modern.js SSR. We are working to discuss the solutions.
